d_model: 512           
n_layers: 6            
n_heads: 8             
d_ff: 2048             
dropout: 0.1           

vocab_size: 10000      
max_len: 5000          
src_padding_idx: 1     
tgt_padding_idx: 1     


weight_decay: 0.01     
label_smoothing: 0.1   
warmup_steps: 4000     
gradient_clip: 1.0     


share_embedding: false      
tie_projection_weights: true